@echo off

call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd" -arch=amd64

SETLOCAL

SET ROOT_DIR=%~dp0
SET BUILD_DIR=%ROOT_DIR%build\
SET CODE_DIR=%ROOT_DIR%code\

if not exist %BUILD_DIR% mkdir %BUILD_DIR%
pushd %BUILD_DIR%

SET COMMON_INCLUDES=/I %CODE_DIR%
SET COMMON_SHARED_LIBS=
SET COMMON_COMPILE_OPTIONS=/MTd /nologo /GR- /EHa /Od /Oi /WX /W4 /wd4201 /wd4100 /wd4109 /FC /Z7 /std:c++17
SET COMMON_LINK_OPTIONS=/incremental:no /opt:ref

del *.pdb >nul 2>&1
SET REX_PDB=rex_%random%.pdb

SET REX_COMPILE_OPTIONS=%COMMON_COMPILE_OPTIONS% /Fe: rex /Fm: rex.map /LD /DREX_EXPORT
SET REX_LINK_OPTIONS=%COMMON_LINK_OPTIONS% /PDB:%REX_PDB%
SET REX_SHARED_LIBS=%COMMON_SHARED_LIBS%

cl %REX_COMPILE_OPTIONS% %CODE_DIR%rex.cpp %REX_LIBS% %COMMON_INCLUDES% /link %REX_LINK_OPTIONS% %REX_SHARED_LIBS%

SET MAIN_COMPILE_OPTIONS=%COMMON_COMPILE_OPTIONS% /Fe: rex.exe /Fm: rex.map /DREX_IMPORT
SET MAIN_LINK_OPTIONS=%COMMON_LINK_OPTIONS%
SET MAIN_SHARED_LIBS=%COMMON_SHARED_LIBS% rex.lib User32.lib Gdi32.lib Winmm.lib
SET MAIN_STATIC_LIBS=

cl %MAIN_COMPILE_OPTIONS% %CODE_DIR%main.cpp %MAIN_STATIC_LIBS% %COMMON_INCLUDES% /link %MAIN_LINK_OPTIONS% %MAIN_SHARED_LIBS%

ENDLOCAL