name: deploy-wasm

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'rex-core/**'
      - 'rex-raster/**'
      - 'rex-viewer/**'
      - '.github/workflows/deploy_wasm.yml'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'rex-core/**'
      - 'rex-raster/**'
      - 'rex-viewer/**'
      - '.github/workflows/deploy_wasm.yml'
      - 'CMakeLists.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.0.0
        actions-cache-folder: 'emsdk-cache'

    - name: Configure CMake
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake

    - name: Build
      run: cmake --build build --target rex-viewer rex-deploy-index -j

    - name: Deploy
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'build/bin'
        destination-github-username: 'WaleedYaser'
        destination-repo: 'rex-wasm'
        user-email: 'waleedyaser95@gmail.com'
