name: package

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        build-variant: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt update
          sudo apt install -y libxcb1-dev libxcb-util-dev libxcb-keysyms1-dev libxcb-image0-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-variant }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build-variant }} -j

    - name: Pack
      working-directory: build
      run: cpack -G ZIP

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: rex-artifact-${{ github.sha }}
        path: build/*.zip
        if-no-files-found: error
        retention-days: 1
