name: unit-tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/pack.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/pack.yml'

jobs:
  build-desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        build-variant: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt update
          sudo apt install -y libxcb1-dev libxcb-util-dev libxcb-keysyms1-dev libxcb-image0-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-variant }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build-variant }} -j

    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.build-variant }}

  build-web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: 3.0.0
        actions-cache-folder: 'emsdk-cache'

    - name: Configure CMake
      run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake

    - name: Build
      run: cmake --build build  -j

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Test
      run: node build/bin/rex-utests.js

    - name: Install
      run: cmake --install build --prefix rex-wasm

    - name: Ref
      run: echo ${{ github.ref }}

    - name: Deploy
      if: github.ref == 'ref/head/main'
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'rex-wasm'
        destination-github-username: 'WaleedYaser'
        destination-repository-name: 'rex-wasm'
        user-email: 'waleedyaser95@gmail.com'
        target-branch: 'main'
