name: unit-tests

on:
  push:
    branches: [ main ]
    paths-ignore: '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore: '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        build-variant: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt update
          sudo apt install -y libxcb1-dev libxcb-util-dev libxcb-keysyms1-dev

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build-variant }}

    - name: Build
      run: cmake --build build --config ${{ matrix.build-variant }} -j

    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.build-variant }}
